### ISSUE TITLE
Questions about pre-trained model

### ISSUE THREAD

**Issue by jialuli-luka** [cshizhe/VLN-HAMT#2]
Hi, 
    Thanks for the great work! 
    I'm trying to directly load the pretrained model you provide "../datasets/R2R/trained_models/vitbase-6tasks-pretrain/model_step_130000.pt" and then fine-tune on r2r task. However, I encounter the problem:

     RuntimeError: Error(s) in loading state_dict for NavCMT:
	size mismatch for bert.hist_embeddings.position_embeddings.weight: copying a param with shape torch.Size([50, 768]) from checkpoint, the shape in current model is torch.Size([100, 768]).

I also followed your provided scripts to pre-train the model (w/o e2e vit), and then fine-tune on r2r, which seems to work fine.   
    Just hope to check whether the provided pre-trained model (w/o e2e vit) is the correct one, and if I need to modify any code/hyperparameter to load the pre-trained model?

   Thanks so much!

**Comment by cshizhe** [comment]
Hi, please change [this line](https://github.com/cshizhe/VLN-HAMT/blob/main/finetune_src/models/vlnbert_init.py#L63) according to the param size of the pretrained model.
