### ISSUE TITLE
Could you sepecify the models that can reproduce the reported results?

### ISSUE THREAD

**Issue by Xin-Ye-1** [cshizhe/VLN-HAMT#6]
Hi Shizhe,

Thank you for releasing the code! I am wondering if you can specify or release the models for us to reproduce the reported results. I would appreciate it greatly if you can provide additional instructions!

**Comment by cshizhe** [comment]
Hi, the pretrained models are released, see https://github.com/cshizhe/VLN-HAMT#installation.
