### ISSUE TITLE
provided features differs from extracted features

### ISSUE THREAD

**Issue by wz0919** [cshizhe/VLN-HAMT#9]
Hi,

Thanks for the great work!

I noticed that if we use `preprocess/precompute_img_features_vit.py` to extract visual features, the outputted features are slightly different from features in provided HDF5 files.
For pretrained ViT-B/16 from TIMM, there's about 0.01 average difference between outputted features and features in `datasets/R2R/features/pth_vit_base_patch16_224_imagenet.hdf5`.
For e2e pretrained ViT-B/16 from `datasets/R2R/trained_models/vitbase-6tasks-pretrain-e2e/model_step_22000.pt`, there's about 0.007 average difference between outputted features and features in `datasets/R2R/features/pth_vit_base_patch16_224_imagenet_r2r.e2e.ft.22k.hdf5`.

I also ensured this isn't caused by  potentially different batchsize in forward step. Feature differences caused by different batchsize shouldn't be around 1e-6.

Could you provide any suggestions on the reason causing these differences?

**Comment by cshizhe** [comment]
Sorry I just found that the timm version is not correct in the requirement.txt.
We used the timm with commit id 9cc7dda6e5fcbbc7ac5ba5d2d44050d2a8e3e38d.
The released vit models are different in the newest timm version.

**Comment by wz0919** [comment]
Many thanks!
